### PR TITLE
Changes onChange event to only trigger on changes inside the editor

### PR DESCRIPTION
**Pull request by n1ru4l**
This implements the behaviour described in #4. However I was not able to create a failing test for this...

### CODE REVIEW

**Comment by kolybasov** [comment]
@n1ru4l thanks for the PR, I will try to review it today.

**Comment by kolybasov** [comment]
@n1ru4l sorry to take so long for review. I think you are trying to do the same as [this method](https://github.com/kolybasov/ember-medium-editor/blob/master/addon/components/medium-editor.js#L186-L193) does 
When  editor receive content it set is as `_prevValue` and then [checks](https://github.com/kolybasov/ember-medium-editor/blob/master/addon/components/medium-editor.js#L147-L152) if content changed.
So I guess it is the reason why you cannot get a failing test and probably your issue has another way to fix. I will check it.

**Comment by n1ru4l** [comment]
Did you test it inside a real application? It seemed to work for me..

**Comment by kolybasov** [comment]
@n1ru4l I din't tested your branch inside real application but I have release version inside of it. And it was fine. I checked your twiddle and problem is definitely exists but this fix is trying to do the same job as `_setContet` + `isUpdated` hack. So we need to find where original one is not working instead of creating two similar hacks.

**Comment by n1ru4l** [comment]
@kolybasov I do not think there is no "clean" way to do it, since this library is a wrapper for a lib that is in first place not designed for using it with ember. Also IMHO my "hack" does not the same as your "hack". Your hack checks if the content has changed. My hack disables the next emission of the onChange event whenever the didUpdateAttrs lifecycle hook is called. At the moment everytime the didUpdateAttrs lifecycle hook is called the onChange event gets emitted. Since the only event we get is the https://github.com/yabwe/medium-editor#capturing-dom-changes event I do not think there is a better way of doing this. Nevertheless I would also like to have a better solution for this...

Here also my test repository: https://github.com/n1ru4l/ember-medium-editor-fix-demo
My meantime solution for me will be to continue using my fork until someone comes up with a fix.

**Comment by n1ru4l** [comment]
@kolybasov Any updates?

**Comment by kolybasov** [comment]
@n1ru4l no updates, sorry. I do not work on medium-editor now, busy with work.

**Comment by willviles** [comment]
@n1ru4l @kolybasov, I'll be active on this project over the coming weeks. I'll get this reviewed and tested over the next few days!

**Comment by n1ru4l** [comment]
@willviles Any updates?

**Comment by willviles** [comment]
@n1ru4l - sorry for the delay, work requirements have changed quite a bit in the last month! 

I've taken a look and I think I may have a different solution for this. However, as I'm mid-way through doing a pretty big overhaul of the addon to use contextual components #6, I'll include it in that. 

So at the moment I'm happy with this change to be merged into master. Cheers! 👍

**Comment by willviles** [comment]
@kolybasov - good to go on a version bump. You can do it, or you can add me as an `npm-owner`.

**Comment by kolybasov** [comment]
@willviles added you as npm owner. Thanks!

**Comment by willviles** [comment]
`0.1.4` published!

**Pull request merged**
